[package]
name = "commands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab = "0.4.4"
anyhow = "1.0.44"
log = "0.4.14"
serde = { version = "1.0.130", features = [ "derive" ] }